# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_auto_20180123_1400'),
        ('helpdesk', '0018_global_tickets'),
    ]

    operations = [
    ]
